nelmio_cors:
    paths:
        '^/api/': 
            allow_origin: ['*']
            forced_allow_origin_value: '*'
            origin_regex: true
            allow_headers: ['Origin', 'X-Requested-With', 'Content-Type', 'Accept', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
